### ISSUE TITLE
Embedded intent standards

### ISSUE THREAD

**Issue by pixelcircuits** [essential-contributions/ERC-7521#105]
Embed common intent standards into the EntryPoint contract for better gas efficiency. Note: Using plain indexes to reference embedded standards will make intents neither chain nor EntryPoint safe, however this could be fixed through a possible future spec change that will add the EntryPoint contract address to the intent object

**Comment by supiket** [comment]
`CallIntentStandard` is embedded to the `EntryPoint` in #97. For embedding other standards, there should be a naming convention that mitigates function name clashes.
