### ISSUE TITLE
Explore gas saving opportunities

### ISSUE THREAD

**Issue by pixelcircuits** [essential-contributions/ERC-7521#70]
Waiting on #69 

Possible gas saving areas to investigate:

- Force solutions to fill in the order array and fail if all segments weren't processed. The thinking is that we could simplify the execution code as well as the `getIntentIndex` function in `IntentSolutionLib` (rough testing shows this to actually increase gas costs by a few thousand, though)
- Make the default intent standard a contract that the entrypoint inherits instead of calls to. This way the code is organized as if it was it's own contract, but should benefit from locating all the code so close together.
- Make `onlyFromIntentStandardExecutingForSender` something that's just a single call to the entrypoint
- A solver using their own abstract account with a fully signed intent vs using a sandbox, but then have to sweep it out at the end
- could probably emit `UserIntentEvent` event right after validation to avoid having to store hashes in memory
- the new standard-per-segment approach means we no longer need to check `if (intent.intentData[segmentIndex].length > 0) {` in `executeIntentSegment`

**Comment by lazyfuhrer** [comment]
May I work on this after #69 @pixelcircuits ?

**Comment by pixelcircuits** [comment]
You don't need my permission or this repo to help improve ERC-7521! Please share any research and insight on improving the spec on the more public [ethereum magicians board](https://ethereum-magicians.org/t/erc-7521-generalized-intents-for-smart-contract-wallets/15840) rather than trying to work directly off this repo. This repo is just one example implementation of ERC-7521 and its' issues are mostly just notes for our internal team. The real TODOs should be discussed on more public channels for any ERC-7521 implementer to be a part of
